ALTER TABLE orders ALTER COLUMN total_amount TYPE BIGINT USING total_amount::BIGINT;

ALTER TABLE order_events ADD COLUMN event_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE order_events ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE reports ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
