BEGIN;

DROP INDEX IF EXISTS idx_orders_user_id;

ALTER TABLE orders
    DROP CONSTRAINT IF EXISTS orders_user_id_fkey;

ALTER TABLE orders
    DROP COLUMN IF EXISTS user_id;

ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS user_info JSONB;

DROP TABLE IF EXISTS users;

COMMIT;