version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: order_fulfillment_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer_ui
    restart: always
    ports:
      - "8085:8080"
    depends_on:
      - postgres

volumes:
  pg_data:
